# Generated by Django 6.0.2 on 2026-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
