# Generated by Django 6.0.2 on 2026-04-21 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_liveconnection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveconnection',
            name='connection_id',
            field=models.UUIDField(unique=True),
        ),
        migrations.AddIndex(
            model_name='liveconnection',
            index=models.Index(fields=['user', 'session'], name='live_liveco_user_id_0d67d7_idx'),
        ),
    ]
