# Generated by Django 6.0.2 on 2026-04-21 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_alter_liveconnection_connection_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcaster_channel', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveStreamMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(default='720p', max_length=20)),
                ('bitrate', models.IntegerField(default=2500)),
                ('fps', models.IntegerField(default=30)),
                ('codec', models.CharField(default='H264', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LiveViewerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveViewerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('total_watch_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='liveconnection',
            name='live_liveco_session_eaf33d_idx',
        ),
        migrations.RemoveIndex(
            model_name='liveconnection',
            name='live_liveco_connect_d050ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='liveconnection',
            name='live_liveco_user_id_0d67d7_idx',
        ),
        migrations.RemoveField(
            model_name='livemessage',
            name='session',
        ),
        migrations.RemoveField(
            model_name='livemessage',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='liveviewer',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='liveviewer',
            name='live_livevi_session_ccdd1e_idx',
        ),
        migrations.AddField(
            model_name='livesession',
            name='max_viewers',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livebroadcast',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast', to='live.livesession'),
        ),
        migrations.AddField(
            model_name='livechatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='live.livesession'),
        ),
        migrations.AddField(
            model_name='livechatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livereaction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='live.livesession'),
        ),
        migrations.AddField(
            model_name='livereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livesignal',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livesignal',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='live.livesession'),
        ),
        migrations.AddField(
            model_name='livestreammeta',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='live.livesession'),
        ),
        migrations.AddField(
            model_name='liveviewerconnection',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='live.livesession'),
        ),
        migrations.AddField(
            model_name='liveviewerconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liveviewerhistory',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live.livesession'),
        ),
        migrations.AddField(
            model_name='liveviewerhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='liveconnection',
            name='session',
        ),
        migrations.RemoveField(
            model_name='liveconnection',
            name='user',
        ),
        migrations.DeleteModel(
            name='LiveMessage',
        ),
        migrations.RemoveField(
            model_name='liveviewer',
            name='session',
        ),
        migrations.RemoveField(
            model_name='liveviewer',
            name='user',
        ),
        migrations.AddIndex(
            model_name='livechatmessage',
            index=models.Index(fields=['session', 'created_at'], name='live_livech_session_469470_idx'),
        ),
        migrations.AddIndex(
            model_name='liveviewerconnection',
            index=models.Index(fields=['session', 'is_active'], name='live_livevi_session_4425df_idx'),
        ),
        migrations.AddIndex(
            model_name='liveviewerconnection',
            index=models.Index(fields=['user'], name='live_livevi_user_id_d36fd9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='liveviewerconnection',
            unique_together={('session', 'user', 'channel_name')},
        ),
        migrations.DeleteModel(
            name='LiveConnection',
        ),
        migrations.DeleteModel(
            name='LiveViewer',
        ),
    ]
