# Generated by Django 6.0.2 on 2026-04-23 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_livebroadcast_livechatmessage_livereaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='livebroadcast',
            name='session',
        ),
        migrations.RemoveIndex(
            model_name='livechatmessage',
            name='live_livech_session_469470_idx',
        ),
        migrations.RemoveField(
            model_name='livereaction',
            name='session',
        ),
        migrations.RemoveField(
            model_name='livereaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='livesignal',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='livesignal',
            name='session',
        ),
        migrations.RemoveField(
            model_name='livestreammeta',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='liveviewerconnection',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='liveviewerconnection',
            name='live_livevi_session_4425df_idx',
        ),
        migrations.RemoveIndex(
            model_name='liveviewerconnection',
            name='live_livevi_user_id_d36fd9_idx',
        ),
        migrations.RemoveField(
            model_name='liveviewerhistory',
            name='session',
        ),
        migrations.RemoveField(
            model_name='liveviewerhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='max_viewers',
        ),
        migrations.AlterField(
            model_name='livesession',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livemessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='live.livesession'),
        ),
        migrations.AddField(
            model_name='livemessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liveviewer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='live.livesession'),
        ),
        migrations.AddField(
            model_name='liveviewer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LiveBroadcast',
        ),
        migrations.RemoveField(
            model_name='livechatmessage',
            name='session',
        ),
        migrations.RemoveField(
            model_name='livechatmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='LiveReaction',
        ),
        migrations.DeleteModel(
            name='LiveSignal',
        ),
        migrations.DeleteModel(
            name='LiveStreamMeta',
        ),
        migrations.RemoveField(
            model_name='liveviewerconnection',
            name='session',
        ),
        migrations.RemoveField(
            model_name='liveviewerconnection',
            name='user',
        ),
        migrations.DeleteModel(
            name='LiveViewerHistory',
        ),
        migrations.AddIndex(
            model_name='liveviewer',
            index=models.Index(fields=['session', 'user'], name='live_livevi_session_ccdd1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='liveviewer',
            unique_together={('session', 'user')},
        ),
        migrations.DeleteModel(
            name='LiveChatMessage',
        ),
        migrations.DeleteModel(
            name='LiveViewerConnection',
        ),
    ]
