# Generated by Django 6.0.2 on 2026-04-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0005_livemessage_liveviewer_remove_livebroadcast_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
